name: Clara Test Linux Base

on: [push, pull_request]

jobs:
  build-and-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install google test and testing the code
        run: |
          cd testing
          git clone https://github.com/google/googletest.git -b release-1.11.0
          cd googletest
          mkdir build
          cd build
          cmake ..
          sudo make install

          echo testing
          cd ..
          cd ..
          mkdir build
          cd build
          cmake ..
          make

          echo ""
          echo "result"
          ./testing_main
    
